<?php

namespace Tests\Feature;

use App\Http\Middleware\VerifyCsrfToken;
use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class CreateCouponTest extends TestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->setBaseRoute('coupons');
        $this->setBaseModel('App\Models\Coupon');
    }

    /** @test */
    public function a_user_can_create_an_coupon()
    {
        $this->signIn();
        $this->create();
    }

    /** @test */
    public function a_user_can_create_cupon_to_group_users_without_products()
    {
        $this->signIn();
        $this->withoutExceptionHandling()->withoutMiddleware(VerifyCsrfToken::class);
        $route = "{$this->base_route}.store";
        $attributes = raw($this->base_model);

        $response = $this->post(route($route), $attributes)
            ->assertSessionHas('message', 'Successfully created')
            ->assertSessionHas('messageType', 's');
    }



}
